### ISSUE TITLE
Set up CI/CD pipeline for branch base deployment

### ISSUE THREAD

**Issue by kozr** [nwplus/monorepo#2]
Set up pipelines for future cmd-f deployment, while keeping in mind how we can modify this for all hackathons.

Ideally set everything up with GitHub actions. This includes Lighthouse CI and any other useful CI. We also want the CD part to work with Amplify.

You have the option to decide if there is a better hosting provider for us in production. We currently use AWS Amplify, Firebase hosting, and GitHub pages which actually may be one too many...

e.g. cmd-f_dev, cmd-f_master

**Comment by yehee** [comment]
- [x] Create branches `cmd-f_main`, `cmd-f_dev`
- [x] Add branch protection rules for `cmd-f_main` branch (same as `main`)
