### ISSUE TITLE
Implement lo-fi Sponsor section for cmd-f

### ISSUE THREAD

**Issue by yehee** [nwplus/monorepo#26]
This issue is considered completed if criteria in #6 are met.

Feel free to add any additional fields that may be useful.

Any fields added must be on buildconfig.json as well to stay consistent.

Main steps:

1. Populate database with different tiers of sponsors https://dev.nwplus.io
2. Set up the environment by adding .env file from Notion. Run `yarn dev` to confirm
3. Create sponsor jsx file with a name that's descriptive
4. Use firebase function `getCollection(targetedHackathon, 'Sponsors')` in index.js under getStaticProps to fetch sponsor data. You can try console.log the data to see if you've retrieved it right.
5. Feed data into the object that gets exported on the bottom of index.js
6. Make the main sponsor section component and import it into index.js
7. Feed sponsor props into the sponsor section component in index.js
8. console.log the props from inside the sponsor section component so you know the props are getting passed through
9. Distribute the sponsors into their own bin based on their ranks
10. Put them into their own separate rows
11. Give the sponsor images specific max-width to limit their sizes for the tier

Final product should display plat sponsors images on top and in-kind at the bottom.

Don't worry about title images and other stuff yet at this point. Just work on fetching data, feeding it as props and display different tiers of sponsors

Report back to Nick once you're finished. Ignore fetching specific sponsor configs for now.

**Comment by kozr** [comment]
@danielshmidov fyi I am refactoring my faq section right now #38 so may want to wait until that's reviewed and merged

**Comment by kozr** [comment]
You're good to go

**Comment by danielshmidov** [comment]
@kozr we did it
