### ISSUE TITLE
Implement website config page on CMS

### ISSUE THREAD

**Issue by kozr** [nwplus/monorepo#34]
Design and implement a new page in CMS for modifying website configs for each hackathon.

Refer to BuildConfig under cmd-f2021

 3 tabs, with componentStyling having an expandable box for each website section.

**Comment by kozr** [comment]
@vincentchiang1 I've reduced your portion to only making and implementing a new page for CMS.

**Comment by ianmah** [comment]
Vincent and I synced about the task to intro him to the codebase and the task. He's planning on starting this week

**Comment by vincentchiang1** [comment]
Ian helped brief me about CMS repo and the ticket this week. i cloned the repo and set up a page/tab for BuildConfig, just figuring out now what kind of elements to use to display the fields and how to read the values

**Comment by vincentchiang1** [comment]
update this week: reading the build config data from firebase now, just need to make it look prettier!

**Comment by vincentchiang1** [comment]
PR is up https://github.com/nwplus/CMS-V2/pull/72
