### ISSUE TITLE
 Implement the ability to add, modify and remove config fields on CMS

### ISSUE THREAD

**Issue by kozr** [nwplus/monorepo#36]
Similar to Intro section by @dchen150 but for a general component targeted for making arbitrary config fields.

Need to be able to specify any keys and some common types of values.

e.g. Under FAQ config section, we'll need the ability to add, remove, and edit many of these components

#34 will create the section box to fit these fields.

**Comment by dchen150** [comment]
https://github.com/nwplus/CMS-V2/pull/73
