### ISSUE TITLE
Implement hi-fi FAQ section for cmd-f

### ISSUE THREAD

**Issue by yehee** [nwplus/monorepo#42]
- Implement hi-fi Hero section for cmd-f according to the [design](https://www.figma.com/file/kWqvtaGbRQcFh6UvPE8ILt/cmd-f-2021?node-id=119%3A2)

**Comment by kozr** [comment]
#49 WIP

**Comment by kozr** [comment]
just got edit access to figma yesterday

**Comment by ianmah** [comment]
havent started

**Comment by kozr** [comment]
@ianmah wait no this is mine go away

**Comment by ianmah** [comment]
oh LOL I meant this for the footer. footer is mine right
