### ISSUE TITLE
Extract what we want as props on the cms

### ISSUE THREAD

**Issue by kozr** [nwplus/monorepo#6]
This is more of an ideation task. What do we need to ensure we have a good outcome.

e.g.
1. y-offset
2. Template styles.

**Comment by rmehri01** [comment]
Templates:
- [ ] Desktop
- [ ] Mobile

Global:
- [ ] Font
- [ ] Background SVG (one whole image)
- [ ] Background colour

Navbar:
- [ ] Font colour 
- [ ] Link to previous year

FAQ:
- [ ] Title image with alt text
- [ ] Vertical space between title and questions
- [ ] Style of single question (text, background colour, border)

Sponsor:
- [ ] Title image with alt text
- [ ] Max width
- [ ] Vertical space between title and sponsor images

Footer:
- [ ] Font colour

All placeable components:
- [ ] Positioning somehow
- [ ] Width and height

Button:
- [ ] Link
- [ ] Background image

Text block:
- [ ] Font size
- [ ] Font colour
