### ISSUE TITLE
Implement "switch"

### ISSUE THREAD

**Issue by kozr** [nwplus/monorepo#8]
The switch will allow us to consume data given by the cms and decide which template to use

Be thoughtful about this component.

Edit: [Dynamic Imports](https://nextjs.org/docs/advanced-features/dynamic-import) is probably the key

**Comment by kozr** [comment]
@rmehri01 may also need to consider how it'll work on cms. It needs to be descriptive on cms

**Comment by rmehri01** [comment]
Hmm, I read up a bit about it but I'm still not really sure how to make it work.

**Comment by kozr** [comment]
dynamic_import(`${props.template}.js`)

**Comment by rmehri01** [comment]
No updates yet, still looking into this.

**Comment by kozr** [comment]
You can ignore this for now @rmehri01 @yungalyx
